apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-node
  namespace: hello
spec:
  template:
    spec:
      containers:
        - image: docker.io/jonnyman9/hello-node
          env:
            - name: TARGET
              value: "Node"
